name       : python-texttable
version    : 1.6.4
release    : 8
source     :
    - https://pypi.io/packages/source/t/texttable/texttable-1.6.4.tar.gz : 42ee7b9e15f7b225747c3fa08f43c5d6c83bc899f80ff9bae9319334824076e9
license    : MIT
component  : programming.python
summary    : Python module for creating simple ASCII tables
description: |
    Python module for creating simple ASCII tables
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
