name       : python-texttable
version    : 0.9.0
release    : 3
source     :
    - https://pypi.python.org/packages/02/fb/ed19f2cc3aff43c6ec8d5aebc1c5f461a7330c6248aa7f56064fcb1346cb/texttable-0.9.0.tar.gz : ea73c237071c3981c90854ed4dcd596d10719e568c606e94ce459e89081a6520
license    : LGPL-3.0
component  : programming.python
summary    : Python module for creating simple ASCII tables
description: |
    Python module for creating simple ASCII tables
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
