name       : python-texttable
version    : 1.6.3
release    : 6
source     :
    - https://pypi.io/packages/source/t/texttable/texttable-1.6.3.tar.gz : ce0faf21aa77d806bbff22b107cc22cce68dc9438f97a2df32c93e9afa4ce436
license    : LGPL-3.0
component  : programming.python
summary    : Python module for creating simple ASCII tables
description: |
    Python module for creating simple ASCII tables
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
