name       : python-texttable
version    : 1.6.7
release    : 9
source     :
    - https://pypi.io/packages/source/t/texttable/texttable-1.6.7.tar.gz : 290348fb67f7746931bcdfd55ac7584ecd4e5b0846ab164333f0794b121760f2
homepage   : https://github.com/foutaise/texttable/
license    : MIT
component  : programming.python
summary    : Python module for creating simple ASCII tables
description: |
    Python module for creating simple ASCII tables
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
